// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "shopify-seller-api",
    "version": "0.1.0"
  },
  "paths": {
    "/health": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/product/{make}": {
      "get": {
        "description": "Return json file for a specific make that will help produces products for seller central.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of the make we want on all product variants.",
            "name": "make",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the the make.",
            "schema": {
              "type": "array",
              "items": {}
            }
          },
          "400": {
            "description": "Invalid \"make\" provided or not available."
          }
        }
      }
    },
    "/swatch/{make}": {
      "get": {
        "description": "Return json file for a specific make that will help produces color swatches.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of the make we want on all color variants.",
            "name": "make",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the the make.",
            "schema": {
              "type": "array",
              "items": {}
            }
          },
          "400": {
            "description": "Invalid \"make\" provided or not available."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "shopify-seller-api",
    "version": "0.1.0"
  },
  "paths": {
    "/health": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/product/{make}": {
      "get": {
        "description": "Return json file for a specific make that will help produces products for seller central.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of the make we want on all product variants.",
            "name": "make",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the the make.",
            "schema": {
              "type": "array",
              "items": {}
            }
          },
          "400": {
            "description": "Invalid \"make\" provided or not available."
          }
        }
      }
    },
    "/swatch/{make}": {
      "get": {
        "description": "Return json file for a specific make that will help produces color swatches.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name of the make we want on all color variants.",
            "name": "make",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the the make.",
            "schema": {
              "type": "array",
              "items": {}
            }
          },
          "400": {
            "description": "Invalid \"make\" provided or not available."
          }
        }
      }
    }
  }
}`))
}
